### ISSUE TITLE
You lost me in the first paragraph...

### ISSUE THREAD

**Issue by radavis** [rishal-hurbans/Robust-REST-Architectures#1]
You could change this document to say: "REST is the mapping of HTTP verbs to CRUD actions", and I would have gotten more out of it than what it is in its current state. 

Less is more.

**Comment by rishal-hurbans** [comment]
Although that is relevant with most HTTP implementations of the style. That is also one of the misconceptions that we were trying to address by giving this talk and writing this article. There's more to REST than just the mapping to HTTP verbs. Thanks for your feedback.
