### ISSUE TITLE
Terminology incorrect

### ISSUE THREAD

**Issue by aoyama-val** [rishal-hurbans/Robust-REST-Architectures#4]
incorrect: http verb
correct: http method

The "/some/path" part of a url is called a "path", not "resource". As the name "Uniform Resource Locator" suggests, whole a URL points a resource.

**Comment by rishal-hurbans** [comment]
We've added a [paragraph](https://github.com/rishal-hurbans/The-REST-Architectural-Style/commit/e0b6272937bf981c916305c39dad70f2d9c3b7a4) clarifying HTTP vs REST terminology. Thank you for the feedback.
